### ISSUE TITLE
Work only with drawable folder name is "-hdpi","-mdpi","-ldpi"

### ISSUE THREAD

**Issue by sondt87** [inmite/android-selector-chapek#1]
In case, I make drawable folder for tablet with name "drawable-sw600dp". When I right click on the folder, this plugin is disabled.

**Comment by arnestockmans** [comment]
I'm having this issue too, but in the "drawable" folder. I wanted to use it to generate a selector for my xml drawables.
Looking at the source code, I see it's limited to "drawable-ldpi", "drawable-mdpi", "drawable-hdpi", "drawable-xhdpi", "drawable-xxhdpi", "drawable-xxxhdpi". Why aren't all "drawable" folders allowed?

**Comment by davidvavra** [comment]
This issue is fixed in version 1.0.2 as celebration for being featured on +Google Developers!

Thanks @tomik-dev for fixing this.
