### ISSUE TITLE
Dont Support 'mipmap-xhdpi' In AndroidStudio 1.2

### ISSUE THREAD

**Issue by ghost** [inmite/android-selector-chapek#9]
Dont Support 'mipmap-xhdpi' In AndroidStudio 1.2

**Comment by fayou147** [comment]
me too

**Comment by icoo000** [comment]
me too

**Comment by steventong** [comment]
+1

**Comment by han361769045** [comment]
希望可以支持 mipmap

**Comment by Mybrc91** [comment]
I have add mipmap support. Download the plugin from [here](https://github.com/Mybrc91/android-selector-chapek/raw/master/plugin/android-selector-chapek-master.zip). @zhengfuwang @fayou147 @icoo1985 @steventong @han361769045

**Comment by louisyonge** [comment]
Doesn't support mipmap folder.

**Comment by Mybrc91** [comment]
@louisyonge Try [it.](https://github.com/Mybrc91/android-selector-chapek/raw/master/plugin/android-selector-chapek-master.zip)

**Comment by louisyonge** [comment]
@Mybrc91 Yeah, your plugin really works! Thanks.

**Comment by Mybrc91** [comment]
@louisyonge 说汉语就可以。。。

**Comment by louisyonge** [comment]
@Mybrc91 老夥計，妳的插件真棒！我敢打賭，整個大陸的上帝網路子民都在為妳歡呼，我向聖母瑪利亞保證。^O^
